name: Submodule Cap Test 
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  
  schedule:
    - cron:  '1 22 * * *'    



jobs:
  # This will build an IPA & Upload the artifact in iOS.zip

  # Jobs to build for SubModuleTestAppA
  build-ios-test:
    runs-on: ubuntu-latest
    steps:
      - name: SubModule iOS Build Test
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 62c167ad
          platform: iOS
          build-type: development
          certificate: ios_dev
          native-config: ios_dev
          upload-artifact: ios
          build-stack: macOS - 2021.10
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
          
    # 
  build-web-test:
    runs-on: ubuntu-latest
    steps:
      - name: SubModule Web Build Test
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 62c167ad
          platform: Web
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}